### PR TITLE
Fix subject category index

### LINKED ISSUE #178: Error when title is blank
```
F, [2017-10-23T19:20:59.099672 #40365] FATAL -- : ActionView::Template::Error (undefined method `[]' for nil:NilClass):
F, [2017-10-23T19:20:59.099839 #40365] FATAL -- :      7:       <%= render_square_thumbnail(doc) %>
     8:     </div>
     9:     <div class="card-header">
    10:       <%= render_doc_title(doc) %>
    11:     </div>
    12:     <div class="card-stats">
    13:     <%= render_brief_doc_metadata(doc) %>
F, [2017-10-23T19:20:59.099882 #40365] FATAL -- :
F, [2017-10-23T19:20:59.099924 #40365] FATAL -- : app/helpers/application_helper.rb:108:in `render_doc_title'
app/views/pages/_recent_documents.html.erb:10:in `block (2 levels) in _app_views_pages__recent_documents_html_erb__855815331909512957_53351340'
app/views/pages/_recent_documents.html.erb:5:in `block in _app_views_pages__recent_documents_html_erb__855815331909512957_53351340'
app/views/pages/_recent_documents.html.erb:3:in `each'
app/views/pages/_recent_documents.html.erb:3:in `_app_views_pages__recent_documents_html_erb__855815331909512957_53351340'
app/views/pages/index.html.erb:23:in `_app_views_pages_index_html_erb__4357843570987510361_24384040'
```

### PR DESCRIPTION
**Pull request by tpendragon**
Closes #178

### CODE REVIEW

File: app/indexers/plum_jsonld_converter.rb [hunk 1]
```diff
@@ -144,7 +145,7 @@ def subject_label
 
     def subject_with_category
       JSON.generate(
-        json["subject"].map do |x|
+        json["subject"].select { |x| x["in_scheme"] }.map do |x|
```
Comment (hackmastera) [inline app/indexers/plum_jsonld_converter.rb]: @tpendragon did this present as a bug in indexing? Does this mean there are records with subjects but not categories? If so I think the subjects won't be shown in the view any more; I removed them there in favor of the new presentation.

maybe we should consider allowing for category to be blank if this seems like an issue.
