### PR TITLE
Fix search history and bookmarks

### LINKED ISSUE #207: Search history and bookmarks are broken
When I have search history or bookmarks, I get an error when I try to view them.

### PR DESCRIPTION
**Pull request by escowles**
Fixes #207 

Thanks for reporting this problem @cjcolvar !

### CODE REVIEW

File: spec/features/search_history_spec.rb [hunk 1]
```diff
@@ -0,0 +1,10 @@
+# frozen_string_literal: true
+require 'rails_helper'
+
+RSpec.feature 'Search History', type: :feature do
+  scenario 'when there is search history' do
```
Comment (hackmastera) [inline spec/features/search_history_spec.rb]: There's never really an end to this sentence...

**Comment by hackmastera** [comment]
It would help me if you could write up an issue with the reported problem. Or is there one and it's just not linked here?
